name: Vulnerability Scanning

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Mobsfscan
        uses: MobSF/mobsfscan@0.3.4
        with:
          args: --sarif -o mobsf.sarif

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: http://testaspnet.vulnweb.com/

      - name: GitHub Workflow artifacts (Nuclei)
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log

      - name: Upload mobsfscan results
        uses: actions/upload-artifact@v2
        with:
          name: mobsf.sarif
          path: mobsf.sarif

  import:
    name: Conviso Findings Importation
    needs: scan
    runs-on: ubuntu-20.04
    container:
      image: convisoappsec/flowcli:unstable
      env:
        FLOW_PROJECT_CODE: ${{ secrets.PROJECT_CODE }}
        FLOW_API_KEY: ${{ secrets.CONVISO_API_KEY }}
        FLOW_API_URL: ${{ secrets.HOMOLOGA_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download mobsfscan result
        uses: actions/download-artifact@v2
        with:
          name: mobsf.sarif

      - name: SARIF Importation
        run: |
          conviso findings import-sarif --input-file mobsf.sarif
