jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Mobsfscan
        uses: MobSF/mobsfscan@0.3.4
        with:
          args: --sarif -o mobsf.sarif

      - name: Upload mobsfscan results to GitHub Workflow artifacts
        if: success() # This ensures the step runs only if the previous steps were successful.
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-sarif
          path: mobsf.sarif

  import:
    needs: scan
    runs-on: ubuntu-20.04
    container:
      image: convisoappsec/flowcli:unstable
      env:
        FLOW_PROJECT_CODE: ${{ secrets.PROJECT_CODE }}
        FLOW_API_KEY: ${{ secrets.CONVISO_API_KEY }}
        FLOW_API_URL: ${{ secrets.HOMOLOGA_URL }}
    steps:
      - name: Download mobsfscan result
        uses: actions/download-artifact@v2
        with:
          name: mobsf-sarif

      - name: SARIF Importation to Conviso
        run: |
          conviso findings import-sarif --input-file mobsf.sarif
